# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'ui_calendar.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(819, 601)
        icon = QIcon(QIcon.fromTheme(u"12"))
        MainWindow.setWindowIcon(icon)
        MainWindow.setWindowOpacity(1.000000000000000)
        MainWindow.setAnimated(False)
        MainWindow.setTabShape(QTabWidget.Rounded)
        MainWindow.setDockOptions(QMainWindow.AllowTabbedDocks)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.central_widget = QWidget(MainWindow)
        self.central_widget.setObjectName(u"central_widget")
        self.horizontalLayoutWidget = QWidget(self.central_widget)
        self.horizontalLayoutWidget.setObjectName(u"horizontalLayoutWidget")
        self.horizontalLayoutWidget.setGeometry(QRect(200, 140, 411, 30))
        self.top_date_layout = QHBoxLayout(self.horizontalLayoutWidget)
        self.top_date_layout.setObjectName(u"top_date_layout")
        self.top_date_layout.setContentsMargins(0, 0, 0, 0)
        self.left_button = QPushButton(self.horizontalLayoutWidget)
        self.left_button.setObjectName(u"left_button")
        self.left_button.setCheckable(False)
        self.left_button.setChecked(False)
        self.left_button.setAutoRepeat(False)
        self.left_button.setAutoExclusive(False)

        self.top_date_layout.addWidget(self.left_button)

        self.year_edit = QSpinBox(self.horizontalLayoutWidget)
        self.year_edit.setObjectName(u"year_edit")
        self.year_edit.setAlignment(Qt.AlignCenter)
        self.year_edit.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.year_edit.setCorrectionMode(QAbstractSpinBox.CorrectToPreviousValue)
        self.year_edit.setMinimum(1500)
        self.year_edit.setMaximum(9999)
        self.year_edit.setStepType(QAbstractSpinBox.DefaultStepType)
        self.year_edit.setValue(2022)

        self.top_date_layout.addWidget(self.year_edit)

        self.month_edit = QSpinBox(self.horizontalLayoutWidget)
        self.month_edit.setObjectName(u"month_edit")
        self.month_edit.setEnabled(True)
        self.month_edit.setFocusPolicy(Qt.WheelFocus)
        self.month_edit.setAcceptDrops(False)
        self.month_edit.setWrapping(True)
        self.month_edit.setFrame(True)
        self.month_edit.setAlignment(Qt.AlignCenter)
        self.month_edit.setReadOnly(False)
        self.month_edit.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.month_edit.setAccelerated(False)
        self.month_edit.setCorrectionMode(QAbstractSpinBox.CorrectToPreviousValue)
        self.month_edit.setProperty("showGroupSeparator", False)
        self.month_edit.setMinimum(0)
        self.month_edit.setMaximum(13)
        self.month_edit.setSingleStep(1)
        self.month_edit.setStepType(QAbstractSpinBox.DefaultStepType)
        self.month_edit.setValue(12)
        self.month_edit.setDisplayIntegerBase(10)

        self.top_date_layout.addWidget(self.month_edit)

        self.next_button = QPushButton(self.horizontalLayoutWidget)
        self.next_button.setObjectName(u"next_button")
        sizePolicy = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.next_button.sizePolicy().hasHeightForWidth())
        self.next_button.setSizePolicy(sizePolicy)
        self.next_button.setContextMenuPolicy(Qt.DefaultContextMenu)
        self.next_button.setStyleSheet(u"brushstyle: solidpattern;")

        self.top_date_layout.addWidget(self.next_button)

        self.calendar = QFrame(self.central_widget)
        self.calendar.setObjectName(u"calendar")
        self.calendar.setGeometry(QRect(200, 170, 411, 321))
        sizePolicy1 = QSizePolicy(QSizePolicy.Maximum, QSizePolicy.Preferred)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.calendar.sizePolicy().hasHeightForWidth())
        self.calendar.setSizePolicy(sizePolicy1)
        self.calendar.setMinimumSize(QSize(0, 0))
        self.calendar.setBaseSize(QSize(650, 400))
        self.calendar.setFrameShape(QFrame.Box)
        self.calendar.setFrameShadow(QFrame.Plain)
        self.calendar.setLineWidth(1)
        self.gridLayout = QGridLayout(self.calendar)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setSizeConstraint(QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(5, 0, 5, 5)
        self.label_0_2 = QLabel(self.calendar)
        self.label_0_2.setObjectName(u"label_0_2")
        sizePolicy2 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Fixed)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(60)
        sizePolicy2.setHeightForWidth(self.label_0_2.sizePolicy().hasHeightForWidth())
        self.label_0_2.setSizePolicy(sizePolicy2)
        self.label_0_2.setMinimumSize(QSize(40, 45))
        font = QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QFont.PreferDefault)
        self.label_0_2.setFont(font)
        self.label_0_2.setMouseTracking(False)
        self.label_0_2.setStyleSheet(u"QLabel:hover {border:1px solid black;}")
        self.label_0_2.setAlignment(Qt.AlignCenter)

        self.gridLayout.addWidget(self.label_0_2, 1, 3, 1, 1)

        self.label_3_6 = QLabel(self.calendar)
        self.label_3_6.setObjectName(u"label_3_6")
        sizePolicy2.setHeightForWidth(self.label_3_6.sizePolicy().hasHeightForWidth())
        self.label_3_6.setSizePolicy(sizePolicy2)
        self.label_3_6.setMinimumSize(QSize(40, 45))
        self.label_3_6.setSizeIncrement(QSize(1, 1))
        self.label_3_6.setFont(font)
        self.label_3_6.setMouseTracking(False)
        self.label_3_6.setStyleSheet(u"QLabel:hover {border:1px solid black;}")
        self.label_3_6.setAlignment(Qt.AlignCenter)

        self.gridLayout.addWidget(self.label_3_6, 5, 7, 1, 1)

        self.label_1_3 = QLabel(self.calendar)
        self.label_1_3.setObjectName(u"label_1_3")
        sizePolicy2.setHeightForWidth(self.label_1_3.sizePolicy().hasHeightForWidth())
        self.label_1_3.setSizePolicy(sizePolicy2)
        self.label_1_3.setMinimumSize(QSize(40, 45))
        self.label_1_3.setFont(font)
        self.label_1_3.setMouseTracking(False)
        self.label_1_3.setStyleSheet(u"QLabel:hover {border:1px solid black;}")
        self.label_1_3.setAlignment(Qt.AlignCenter)

        self.gridLayout.addWidget(self.label_1_3, 2, 4, 1, 1)

        self.label_4_1 = QLabel(self.calendar)
        self.label_4_1.setObjectName(u"label_4_1")
        sizePolicy2.setHeightForWidth(self.label_4_1.sizePolicy().hasHeightForWidth())
        self.label_4_1.setSizePolicy(sizePolicy2)
        self.label_4_1.setMinimumSize(QSize(40, 45))
        self.label_4_1.setFont(font)
        self.label_4_1.setMouseTracking(False)
        self.label_4_1.setStyleSheet(u"QLabel:hover {border:1px solid black;}")
        self.label_4_1.setAlignment(Qt.AlignCenter)

        self.gridLayout.addWidget(self.label_4_1, 6, 2, 1, 1)

        self.label_5_1 = QLabel(self.calendar)
        self.label_5_1.setObjectName(u"label_5_1")
        sizePolicy2.setHeightForWidth(self.label_5_1.sizePolicy().hasHeightForWidth())
        self.label_5_1.setSizePolicy(sizePolicy2)
        self.label_5_1.setMinimumSize(QSize(40, 45))
        self.label_5_1.setFont(font)
        self.label_5_1.setMouseTracking(False)
        self.label_5_1.setStyleSheet(u"QLabel:hover {border:1px solid black;}")
        self.label_5_1.setAlignment(Qt.AlignCenter)

        self.gridLayout.addWidget(self.label_5_1, 7, 2, 1, 1)

        self.label_0_4 = QLabel(self.calendar)
        self.label_0_4.setObjectName(u"label_0_4")
        sizePolicy2.setHeightForWidth(self.label_0_4.sizePolicy().hasHeightForWidth())
        self.label_0_4.setSizePolicy(sizePolicy2)
        self.label_0_4.setMinimumSize(QSize(40, 45))
        self.label_0_4.setFont(font)
        self.label_0_4.setMouseTracking(False)
        self.label_0_4.setStyleSheet(u"QLabel:hover {border:1px solid black;}")
        self.label_0_4.setAlignment(Qt.AlignCenter)

        self.gridLayout.addWidget(self.label_0_4, 1, 5, 1, 1)

        self.label_1_4 = QLabel(self.calendar)
        self.label_1_4.setObjectName(u"label_1_4")
        sizePolicy2.setHeightForWidth(self.label_1_4.sizePolicy().hasHeightForWidth())
        self.label_1_4.setSizePolicy(sizePolicy2)
        self.label_1_4.setMinimumSize(QSize(40, 45))
        self.label_1_4.setFont(font)
        self.label_1_4.setMouseTracking(False)
        self.label_1_4.setStyleSheet(u"QLabel:hover {border:1px solid black;}")
        self.label_1_4.setAlignment(Qt.AlignCenter)

        self.gridLayout.addWidget(self.label_1_4, 2, 5, 1, 1)

        self.week_5 = QLabel(self.calendar)
        self.week_5.setObjectName(u"week_5")
        sizePolicy3 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.week_5.sizePolicy().hasHeightForWidth())
        self.week_5.setSizePolicy(sizePolicy3)
        self.week_5.setMinimumSize(QSize(40, 50))
        self.week_5.setAlignment(Qt.AlignCenter)

        self.gridLayout.addWidget(self.week_5, 0, 6, 1, 1)

        self.label_3_3 = QLabel(self.calendar)
        self.label_3_3.setObjectName(u"label_3_3")
        sizePolicy2.setHeightForWidth(self.label_3_3.sizePolicy().hasHeightForWidth())
        self.label_3_3.setSizePolicy(sizePolicy2)
        self.label_3_3.setMinimumSize(QSize(40, 45))
        self.label_3_3.setFont(font)
        self.label_3_3.setMouseTracking(False)
        self.label_3_3.setStyleSheet(u"QLabel:hover {border:1px solid black;}")
        self.label_3_3.setAlignment(Qt.AlignCenter)

        self.gridLayout.addWidget(self.label_3_3, 5, 4, 1, 1)

        self.label_3_5 = QLabel(self.calendar)
        self.label_3_5.setObjectName(u"label_3_5")
        sizePolicy2.setHeightForWidth(self.label_3_5.sizePolicy().hasHeightForWidth())
        self.label_3_5.setSizePolicy(sizePolicy2)
        self.label_3_5.setMinimumSize(QSize(40, 45))
        self.label_3_5.setFont(font)
        self.label_3_5.setMouseTracking(False)
        self.label_3_5.setStyleSheet(u"QLabel:hover {border:1px solid black;}")
        self.label_3_5.setAlignment(Qt.AlignCenter)

        self.gridLayout.addWidget(self.label_3_5, 5, 6, 1, 1)

        self.label_3_2 = QLabel(self.calendar)
        self.label_3_2.setObjectName(u"label_3_2")
        sizePolicy2.setHeightForWidth(self.label_3_2.sizePolicy().hasHeightForWidth())
        self.label_3_2.setSizePolicy(sizePolicy2)
        self.label_3_2.setMinimumSize(QSize(40, 45))
        self.label_3_2.setFont(font)
        self.label_3_2.setMouseTracking(False)
        self.label_3_2.setStyleSheet(u"QLabel:hover {border:1px solid black;}")
        self.label_3_2.setAlignment(Qt.AlignCenter)

        self.gridLayout.addWidget(self.label_3_2, 5, 3, 1, 1)

        self.label_4_2 = QLabel(self.calendar)
        self.label_4_2.setObjectName(u"label_4_2")
        sizePolicy2.setHeightForWidth(self.label_4_2.sizePolicy().hasHeightForWidth())
        self.label_4_2.setSizePolicy(sizePolicy2)
        self.label_4_2.setMinimumSize(QSize(40, 45))
        self.label_4_2.setFont(font)
        self.label_4_2.setMouseTracking(False)
        self.label_4_2.setStyleSheet(u"QLabel:hover {border:1px solid black;}")
        self.label_4_2.setAlignment(Qt.AlignCenter)

        self.gridLayout.addWidget(self.label_4_2, 6, 3, 1, 1)

        self.label_5_2 = QLabel(self.calendar)
        self.label_5_2.setObjectName(u"label_5_2")
        sizePolicy2.setHeightForWidth(self.label_5_2.sizePolicy().hasHeightForWidth())
        self.label_5_2.setSizePolicy(sizePolicy2)
        self.label_5_2.setMinimumSize(QSize(40, 45))
        self.label_5_2.setFont(font)
        self.label_5_2.setMouseTracking(False)
        self.label_5_2.setStyleSheet(u"QLabel:hover {border:1px solid black;}")
        self.label_5_2.setAlignment(Qt.AlignCenter)

        self.gridLayout.addWidget(self.label_5_2, 7, 3, 1, 1)

        self.week_4 = QLabel(self.calendar)
        self.week_4.setObjectName(u"week_4")
        sizePolicy3.setHeightForWidth(self.week_4.sizePolicy().hasHeightForWidth())
        self.week_4.setSizePolicy(sizePolicy3)
        self.week_4.setMinimumSize(QSize(40, 50))
        self.week_4.setAlignment(Qt.AlignCenter)

        self.gridLayout.addWidget(self.week_4, 0, 5, 1, 1)

        self.label_1_2 = QLabel(self.calendar)
        self.label_1_2.setObjectName(u"label_1_2")
        sizePolicy2.setHeightForWidth(self.label_1_2.sizePolicy().hasHeightForWidth())
        self.label_1_2.setSizePolicy(sizePolicy2)
        self.label_1_2.setMinimumSize(QSize(40, 45))
        self.label_1_2.setFont(font)
        self.label_1_2.setMouseTracking(False)
        self.label_1_2.setStyleSheet(u"QLabel:hover {border:1px solid black;}")
        self.label_1_2.setAlignment(Qt.AlignCenter)

        self.gridLayout.addWidget(self.label_1_2, 2, 3, 1, 1)

        self.week_2 = QLabel(self.calendar)
        self.week_2.setObjectName(u"week_2")
        sizePolicy3.setHeightForWidth(self.week_2.sizePolicy().hasHeightForWidth())
        self.week_2.setSizePolicy(sizePolicy3)
        self.week_2.setMinimumSize(QSize(40, 50))
        self.week_2.setAlignment(Qt.AlignCenter)

        self.gridLayout.addWidget(self.week_2, 0, 3, 1, 1)

        self.label_0_0 = QLabel(self.calendar)
        self.label_0_0.setObjectName(u"label_0_0")
        sizePolicy2.setHeightForWidth(self.label_0_0.sizePolicy().hasHeightForWidth())
        self.label_0_0.setSizePolicy(sizePolicy2)
        self.label_0_0.setMinimumSize(QSize(40, 45))
        self.label_0_0.setFont(font)
        self.label_0_0.setMouseTracking(False)
        self.label_0_0.setStyleSheet(u"QLabel:hover {\n"
"	border:1px solid black;\n"
"}\n"
"QLabel:pressed {\n"
"	background-color: rgb(0, 170, 255);\n"
"}")
        self.label_0_0.setAlignment(Qt.AlignCenter)

        self.gridLayout.addWidget(self.label_0_0, 1, 0, 1, 1)

        self.label_1_6 = QLabel(self.calendar)
        self.label_1_6.setObjectName(u"label_1_6")
        sizePolicy2.setHeightForWidth(self.label_1_6.sizePolicy().hasHeightForWidth())
        self.label_1_6.setSizePolicy(sizePolicy2)
        self.label_1_6.setMinimumSize(QSize(40, 45))
        self.label_1_6.setFont(font)
        self.label_1_6.setMouseTracking(False)
        self.label_1_6.setStyleSheet(u"QLabel:hover {border:1px solid black;}")
        self.label_1_6.setAlignment(Qt.AlignCenter)

        self.gridLayout.addWidget(self.label_1_6, 2, 7, 1, 1)

        self.label_2_0 = QLabel(self.calendar)
        self.label_2_0.setObjectName(u"label_2_0")
        sizePolicy2.setHeightForWidth(self.label_2_0.sizePolicy().hasHeightForWidth())
        self.label_2_0.setSizePolicy(sizePolicy2)
        self.label_2_0.setMinimumSize(QSize(40, 45))
        self.label_2_0.setFont(font)
        self.label_2_0.setMouseTracking(False)
        self.label_2_0.setStyleSheet(u"QLabel:hover {border:1px solid black;}")
        self.label_2_0.setAlignment(Qt.AlignCenter)

        self.gridLayout.addWidget(self.label_2_0, 4, 0, 1, 1)

        self.label_5_5 = QLabel(self.calendar)
        self.label_5_5.setObjectName(u"label_5_5")
        sizePolicy2.setHeightForWidth(self.label_5_5.sizePolicy().hasHeightForWidth())
        self.label_5_5.setSizePolicy(sizePolicy2)
        self.label_5_5.setMinimumSize(QSize(40, 45))
        self.label_5_5.setFont(font)
        self.label_5_5.setMouseTracking(False)
        self.label_5_5.setStyleSheet(u"QLabel:hover {border:1px solid black;}")
        self.label_5_5.setAlignment(Qt.AlignCenter)

        self.gridLayout.addWidget(self.label_5_5, 7, 6, 1, 1)

        self.week_1 = QLabel(self.calendar)
        self.week_1.setObjectName(u"week_1")
        sizePolicy3.setHeightForWidth(self.week_1.sizePolicy().hasHeightForWidth())
        self.week_1.setSizePolicy(sizePolicy3)
        self.week_1.setMinimumSize(QSize(40, 50))
        self.week_1.setAlignment(Qt.AlignCenter)

        self.gridLayout.addWidget(self.week_1, 0, 2, 1, 1)

        self.week_3 = QLabel(self.calendar)
        self.week_3.setObjectName(u"week_3")
        sizePolicy3.setHeightForWidth(self.week_3.sizePolicy().hasHeightForWidth())
        self.week_3.setSizePolicy(sizePolicy3)
        self.week_3.setMinimumSize(QSize(40, 50))
        self.week_3.setAlignment(Qt.AlignCenter)

        self.gridLayout.addWidget(self.week_3, 0, 4, 1, 1)

        self.label_4_3 = QLabel(self.calendar)
        self.label_4_3.setObjectName(u"label_4_3")
        sizePolicy2.setHeightForWidth(self.label_4_3.sizePolicy().hasHeightForWidth())
        self.label_4_3.setSizePolicy(sizePolicy2)
        self.label_4_3.setMinimumSize(QSize(40, 45))
        self.label_4_3.setFont(font)
        self.label_4_3.setMouseTracking(False)
        self.label_4_3.setStyleSheet(u"QLabel:hover {border:1px solid black;}")
        self.label_4_3.setAlignment(Qt.AlignCenter)

        self.gridLayout.addWidget(self.label_4_3, 6, 4, 1, 1)

        self.label_2_3 = QLabel(self.calendar)
        self.label_2_3.setObjectName(u"label_2_3")
        sizePolicy2.setHeightForWidth(self.label_2_3.sizePolicy().hasHeightForWidth())
        self.label_2_3.setSizePolicy(sizePolicy2)
        self.label_2_3.setMinimumSize(QSize(40, 45))
        self.label_2_3.setFont(font)
        self.label_2_3.setMouseTracking(False)
        self.label_2_3.setStyleSheet(u"QLabel:hover {border:1px solid black;}")
        self.label_2_3.setAlignment(Qt.AlignCenter)

        self.gridLayout.addWidget(self.label_2_3, 4, 4, 1, 1)

        self.week_0 = QLabel(self.calendar)
        self.week_0.setObjectName(u"week_0")
        self.week_0.setEnabled(True)
        sizePolicy4 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Fixed)
        sizePolicy4.setHorizontalStretch(0)
        sizePolicy4.setVerticalStretch(0)
        sizePolicy4.setHeightForWidth(self.week_0.sizePolicy().hasHeightForWidth())
        self.week_0.setSizePolicy(sizePolicy4)
        self.week_0.setMinimumSize(QSize(40, 50))
        self.week_0.setLayoutDirection(Qt.LeftToRight)
        self.week_0.setAlignment(Qt.AlignCenter)
        self.week_0.setWordWrap(False)
        self.week_0.setOpenExternalLinks(False)

        self.gridLayout.addWidget(self.week_0, 0, 0, 1, 1)

        self.label_4_4 = QLabel(self.calendar)
        self.label_4_4.setObjectName(u"label_4_4")
        sizePolicy2.setHeightForWidth(self.label_4_4.sizePolicy().hasHeightForWidth())
        self.label_4_4.setSizePolicy(sizePolicy2)
        self.label_4_4.setMinimumSize(QSize(40, 45))
        self.label_4_4.setFont(font)
        self.label_4_4.setMouseTracking(False)
        self.label_4_4.setStyleSheet(u"QLabel:hover {border:1px solid black;}")
        self.label_4_4.setAlignment(Qt.AlignCenter)

        self.gridLayout.addWidget(self.label_4_4, 6, 5, 1, 1)

        self.label_0_3 = QLabel(self.calendar)
        self.label_0_3.setObjectName(u"label_0_3")
        sizePolicy2.setHeightForWidth(self.label_0_3.sizePolicy().hasHeightForWidth())
        self.label_0_3.setSizePolicy(sizePolicy2)
        self.label_0_3.setMinimumSize(QSize(40, 45))
        self.label_0_3.setFont(font)
        self.label_0_3.setMouseTracking(False)
        self.label_0_3.setStyleSheet(u"QLabel:hover {border:1px solid black;}")
        self.label_0_3.setAlignment(Qt.AlignCenter)

        self.gridLayout.addWidget(self.label_0_3, 1, 4, 1, 1)

        self.label_2_4 = QLabel(self.calendar)
        self.label_2_4.setObjectName(u"label_2_4")
        sizePolicy2.setHeightForWidth(self.label_2_4.sizePolicy().hasHeightForWidth())
        self.label_2_4.setSizePolicy(sizePolicy2)
        self.label_2_4.setMinimumSize(QSize(40, 45))
        self.label_2_4.setFont(font)
        self.label_2_4.setMouseTracking(False)
        self.label_2_4.setStyleSheet(u"QLabel:hover {border:1px solid black;}")
        self.label_2_4.setAlignment(Qt.AlignCenter)

        self.gridLayout.addWidget(self.label_2_4, 4, 5, 1, 1)

        self.label_4_6 = QLabel(self.calendar)
        self.label_4_6.setObjectName(u"label_4_6")
        sizePolicy2.setHeightForWidth(self.label_4_6.sizePolicy().hasHeightForWidth())
        self.label_4_6.setSizePolicy(sizePolicy2)
        self.label_4_6.setMinimumSize(QSize(40, 45))
        self.label_4_6.setFont(font)
        self.label_4_6.setMouseTracking(False)
        self.label_4_6.setStyleSheet(u"QLabel:hover {border:1px solid black;}")
        self.label_4_6.setAlignment(Qt.AlignCenter)

        self.gridLayout.addWidget(self.label_4_6, 6, 7, 1, 1)

        self.label_0_1 = QLabel(self.calendar)
        self.label_0_1.setObjectName(u"label_0_1")
        sizePolicy2.setHeightForWidth(self.label_0_1.sizePolicy().hasHeightForWidth())
        self.label_0_1.setSizePolicy(sizePolicy2)
        self.label_0_1.setMinimumSize(QSize(40, 45))
        self.label_0_1.setFont(font)
        self.label_0_1.setMouseTracking(False)
        self.label_0_1.setStyleSheet(u"QLabel:hover {border:1px solid black;}")
        self.label_0_1.setAlignment(Qt.AlignCenter)

        self.gridLayout.addWidget(self.label_0_1, 1, 2, 1, 1)

        self.label_1_0 = QLabel(self.calendar)
        self.label_1_0.setObjectName(u"label_1_0")
        sizePolicy2.setHeightForWidth(self.label_1_0.sizePolicy().hasHeightForWidth())
        self.label_1_0.setSizePolicy(sizePolicy2)
        self.label_1_0.setMinimumSize(QSize(40, 45))
        self.label_1_0.setFont(font)
        self.label_1_0.setMouseTracking(False)
        self.label_1_0.setStyleSheet(u"QLabel:hover {border:1px solid black;}")
        self.label_1_0.setAlignment(Qt.AlignCenter)

        self.gridLayout.addWidget(self.label_1_0, 2, 0, 1, 1)

        self.label_5_0 = QLabel(self.calendar)
        self.label_5_0.setObjectName(u"label_5_0")
        sizePolicy2.setHeightForWidth(self.label_5_0.sizePolicy().hasHeightForWidth())
        self.label_5_0.setSizePolicy(sizePolicy2)
        self.label_5_0.setMinimumSize(QSize(40, 45))
        self.label_5_0.setFont(font)
        self.label_5_0.setMouseTracking(False)
        self.label_5_0.setStyleSheet(u"QLabel:hover {border:1px solid black;}")
        self.label_5_0.setAlignment(Qt.AlignCenter)

        self.gridLayout.addWidget(self.label_5_0, 7, 0, 1, 1)

        self.label_2_6 = QLabel(self.calendar)
        self.label_2_6.setObjectName(u"label_2_6")
        sizePolicy2.setHeightForWidth(self.label_2_6.sizePolicy().hasHeightForWidth())
        self.label_2_6.setSizePolicy(sizePolicy2)
        self.label_2_6.setMinimumSize(QSize(40, 45))
        font1 = QFont()
        font1.setPointSize(10)
        self.label_2_6.setFont(font1)
        self.label_2_6.setMouseTracking(False)
        self.label_2_6.setStyleSheet(u"QLabel:hover {border:1px solid black;}")
        self.label_2_6.setAlignment(Qt.AlignCenter)

        self.gridLayout.addWidget(self.label_2_6, 4, 7, 1, 1)

        self.label_5_6 = QLabel(self.calendar)
        self.label_5_6.setObjectName(u"label_5_6")
        sizePolicy2.setHeightForWidth(self.label_5_6.sizePolicy().hasHeightForWidth())
        self.label_5_6.setSizePolicy(sizePolicy2)
        self.label_5_6.setMinimumSize(QSize(40, 45))
        self.label_5_6.setFont(font)
        self.label_5_6.setMouseTracking(False)
        self.label_5_6.setStyleSheet(u"QLabel:hover {border:1px solid black;}")
        self.label_5_6.setAlignment(Qt.AlignCenter)

        self.gridLayout.addWidget(self.label_5_6, 7, 7, 1, 1)

        self.label_2_1 = QLabel(self.calendar)
        self.label_2_1.setObjectName(u"label_2_1")
        sizePolicy2.setHeightForWidth(self.label_2_1.sizePolicy().hasHeightForWidth())
        self.label_2_1.setSizePolicy(sizePolicy2)
        self.label_2_1.setMinimumSize(QSize(40, 45))
        self.label_2_1.setFont(font)
        self.label_2_1.setMouseTracking(False)
        self.label_2_1.setStyleSheet(u"QLabel:hover {border:1px solid black;}")
        self.label_2_1.setAlignment(Qt.AlignCenter)

        self.gridLayout.addWidget(self.label_2_1, 4, 2, 1, 1)

        self.label_4_5 = QLabel(self.calendar)
        self.label_4_5.setObjectName(u"label_4_5")
        sizePolicy2.setHeightForWidth(self.label_4_5.sizePolicy().hasHeightForWidth())
        self.label_4_5.setSizePolicy(sizePolicy2)
        self.label_4_5.setMinimumSize(QSize(40, 45))
        self.label_4_5.setFont(font)
        self.label_4_5.setMouseTracking(False)
        self.label_4_5.setStyleSheet(u"QLabel:hover {border:1px solid black;}")
        self.label_4_5.setAlignment(Qt.AlignCenter)

        self.gridLayout.addWidget(self.label_4_5, 6, 6, 1, 1)

        self.label_0_5 = QLabel(self.calendar)
        self.label_0_5.setObjectName(u"label_0_5")
        sizePolicy2.setHeightForWidth(self.label_0_5.sizePolicy().hasHeightForWidth())
        self.label_0_5.setSizePolicy(sizePolicy2)
        self.label_0_5.setMinimumSize(QSize(40, 45))
        self.label_0_5.setFont(font)
        self.label_0_5.setMouseTracking(False)
        self.label_0_5.setStyleSheet(u"QLabel:hover {border:1px solid black;}")
        self.label_0_5.setAlignment(Qt.AlignCenter)

        self.gridLayout.addWidget(self.label_0_5, 1, 6, 1, 1)

        self.label_5_3 = QLabel(self.calendar)
        self.label_5_3.setObjectName(u"label_5_3")
        sizePolicy2.setHeightForWidth(self.label_5_3.sizePolicy().hasHeightForWidth())
        self.label_5_3.setSizePolicy(sizePolicy2)
        self.label_5_3.setMinimumSize(QSize(40, 45))
        self.label_5_3.setFont(font)
        self.label_5_3.setMouseTracking(False)
        self.label_5_3.setStyleSheet(u"QLabel:hover {border:1px solid black;}")
        self.label_5_3.setAlignment(Qt.AlignCenter)

        self.gridLayout.addWidget(self.label_5_3, 7, 4, 1, 1)

        self.label_3_4 = QLabel(self.calendar)
        self.label_3_4.setObjectName(u"label_3_4")
        sizePolicy2.setHeightForWidth(self.label_3_4.sizePolicy().hasHeightForWidth())
        self.label_3_4.setSizePolicy(sizePolicy2)
        self.label_3_4.setMinimumSize(QSize(40, 45))
        self.label_3_4.setFont(font)
        self.label_3_4.setMouseTracking(False)
        self.label_3_4.setStyleSheet(u"QLabel:hover {border:1px solid black;}")
        self.label_3_4.setAlignment(Qt.AlignCenter)

        self.gridLayout.addWidget(self.label_3_4, 5, 5, 1, 1)

        self.label_3_0 = QLabel(self.calendar)
        self.label_3_0.setObjectName(u"label_3_0")
        sizePolicy2.setHeightForWidth(self.label_3_0.sizePolicy().hasHeightForWidth())
        self.label_3_0.setSizePolicy(sizePolicy2)
        self.label_3_0.setMinimumSize(QSize(40, 45))
        self.label_3_0.setFont(font)
        self.label_3_0.setMouseTracking(False)
        self.label_3_0.setStyleSheet(u"QLabel:hover {border:1px solid black;}")
        self.label_3_0.setAlignment(Qt.AlignCenter)

        self.gridLayout.addWidget(self.label_3_0, 5, 0, 1, 1)

        self.label_2_5 = QLabel(self.calendar)
        self.label_2_5.setObjectName(u"label_2_5")
        sizePolicy2.setHeightForWidth(self.label_2_5.sizePolicy().hasHeightForWidth())
        self.label_2_5.setSizePolicy(sizePolicy2)
        self.label_2_5.setMinimumSize(QSize(40, 45))
        self.label_2_5.setFont(font)
        self.label_2_5.setMouseTracking(False)
        self.label_2_5.setStyleSheet(u"QLabel:hover {border:1px solid black;}")
        self.label_2_5.setAlignment(Qt.AlignCenter)

        self.gridLayout.addWidget(self.label_2_5, 4, 6, 1, 1)

        self.label_3_1 = QLabel(self.calendar)
        self.label_3_1.setObjectName(u"label_3_1")
        sizePolicy2.setHeightForWidth(self.label_3_1.sizePolicy().hasHeightForWidth())
        self.label_3_1.setSizePolicy(sizePolicy2)
        self.label_3_1.setMinimumSize(QSize(40, 45))
        self.label_3_1.setFont(font)
        self.label_3_1.setMouseTracking(False)
        self.label_3_1.setStyleSheet(u"QLabel:hover {border:1px solid black;}")
        self.label_3_1.setAlignment(Qt.AlignCenter)

        self.gridLayout.addWidget(self.label_3_1, 5, 2, 1, 1)

        self.label_4_0 = QLabel(self.calendar)
        self.label_4_0.setObjectName(u"label_4_0")
        sizePolicy2.setHeightForWidth(self.label_4_0.sizePolicy().hasHeightForWidth())
        self.label_4_0.setSizePolicy(sizePolicy2)
        self.label_4_0.setMinimumSize(QSize(40, 45))
        self.label_4_0.setFont(font)
        self.label_4_0.setMouseTracking(False)
        self.label_4_0.setStyleSheet(u"QLabel:hover {border:1px solid black;}")
        self.label_4_0.setAlignment(Qt.AlignCenter)

        self.gridLayout.addWidget(self.label_4_0, 6, 0, 1, 1)

        self.label_2_2 = QLabel(self.calendar)
        self.label_2_2.setObjectName(u"label_2_2")
        sizePolicy2.setHeightForWidth(self.label_2_2.sizePolicy().hasHeightForWidth())
        self.label_2_2.setSizePolicy(sizePolicy2)
        self.label_2_2.setMinimumSize(QSize(40, 45))
        self.label_2_2.setFont(font)
        self.label_2_2.setMouseTracking(False)
        self.label_2_2.setStyleSheet(u"QLabel:hover {border:1px solid black;}")
        self.label_2_2.setAlignment(Qt.AlignCenter)

        self.gridLayout.addWidget(self.label_2_2, 4, 3, 1, 1)

        self.week_6 = QLabel(self.calendar)
        self.week_6.setObjectName(u"week_6")
        self.week_6.setEnabled(True)
        sizePolicy5 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Minimum)
        sizePolicy5.setHorizontalStretch(0)
        sizePolicy5.setVerticalStretch(0)
        sizePolicy5.setHeightForWidth(self.week_6.sizePolicy().hasHeightForWidth())
        self.week_6.setSizePolicy(sizePolicy5)
        self.week_6.setMinimumSize(QSize(40, 50))
        self.week_6.setScaledContents(False)
        self.week_6.setAlignment(Qt.AlignCenter)
        self.week_6.setWordWrap(False)
        self.week_6.setMargin(2)

        self.gridLayout.addWidget(self.week_6, 0, 7, 1, 1)

        self.label_1_5 = QLabel(self.calendar)
        self.label_1_5.setObjectName(u"label_1_5")
        sizePolicy2.setHeightForWidth(self.label_1_5.sizePolicy().hasHeightForWidth())
        self.label_1_5.setSizePolicy(sizePolicy2)
        self.label_1_5.setMinimumSize(QSize(40, 45))
        self.label_1_5.setFont(font)
        self.label_1_5.setMouseTracking(False)
        self.label_1_5.setStyleSheet(u"QLabel:hover {border:1px solid black;}")
        self.label_1_5.setAlignment(Qt.AlignCenter)

        self.gridLayout.addWidget(self.label_1_5, 2, 6, 1, 1)

        self.label_0_6 = QLabel(self.calendar)
        self.label_0_6.setObjectName(u"label_0_6")
        sizePolicy2.setHeightForWidth(self.label_0_6.sizePolicy().hasHeightForWidth())
        self.label_0_6.setSizePolicy(sizePolicy2)
        self.label_0_6.setMinimumSize(QSize(40, 45))
        self.label_0_6.setFont(font)
        self.label_0_6.setMouseTracking(False)
        self.label_0_6.setStyleSheet(u"QLabel:hover {border:1px solid black;}")
        self.label_0_6.setAlignment(Qt.AlignCenter)

        self.gridLayout.addWidget(self.label_0_6, 1, 7, 1, 1)

        self.label_5_4 = QLabel(self.calendar)
        self.label_5_4.setObjectName(u"label_5_4")
        sizePolicy2.setHeightForWidth(self.label_5_4.sizePolicy().hasHeightForWidth())
        self.label_5_4.setSizePolicy(sizePolicy2)
        self.label_5_4.setMinimumSize(QSize(40, 45))
        self.label_5_4.setFont(font)
        self.label_5_4.setMouseTracking(False)
        self.label_5_4.setStyleSheet(u"QLabel:hover {border:1px solid black;}")
        self.label_5_4.setAlignment(Qt.AlignCenter)

        self.gridLayout.addWidget(self.label_5_4, 7, 5, 1, 1)

        self.label_1_1 = QLabel(self.calendar)
        self.label_1_1.setObjectName(u"label_1_1")
        sizePolicy2.setHeightForWidth(self.label_1_1.sizePolicy().hasHeightForWidth())
        self.label_1_1.setSizePolicy(sizePolicy2)
        self.label_1_1.setMinimumSize(QSize(40, 45))
        self.label_1_1.setFont(font)
        self.label_1_1.setMouseTracking(False)
        self.label_1_1.setStyleSheet(u"QLabel:hover {border:1px solid black;}")
        self.label_1_1.setAlignment(Qt.AlignCenter)

        self.gridLayout.addWidget(self.label_1_1, 2, 2, 1, 1)

        MainWindow.setCentralWidget(self.central_widget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 819, 26))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        self.statusbar.setSizeGripEnabled(False)
        MainWindow.setStatusBar(self.statusbar)
#if QT_CONFIG(shortcut)
#endif // QT_CONFIG(shortcut)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"KFC Calendar", None))
        self.left_button.setText(QCoreApplication.translate("MainWindow", u"<", None))
        self.year_edit.setSuffix(QCoreApplication.translate("MainWindow", u"\u5e74", None))
        self.month_edit.setSuffix(QCoreApplication.translate("MainWindow", u"\u6708", None))
        self.next_button.setText(QCoreApplication.translate("MainWindow", u">", None))
        self.label_0_2.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_3_6.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_1_3.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_4_1.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_5_1.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_0_4.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_1_4.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.week_5.setText(QCoreApplication.translate("MainWindow", u"\u661f\u671f\u516d", None))
        self.label_3_3.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_3_5.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_3_2.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_4_2.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_5_2.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.week_4.setText(QCoreApplication.translate("MainWindow", u"\u661f\u671f\u4e94", None))
        self.label_1_2.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.week_2.setText(QCoreApplication.translate("MainWindow", u"\u661f\u671f\u4e09", None))
        self.label_0_0.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_1_6.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_2_0.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_5_5.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.week_1.setText(QCoreApplication.translate("MainWindow", u"\u661f\u671f\u4e8c", None))
        self.week_3.setText(QCoreApplication.translate("MainWindow", u"\u661f\u671f\u56db", None))
        self.label_4_3.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_2_3.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.week_0.setText(QCoreApplication.translate("MainWindow", u"\u661f\u671f\u4e00", None))
        self.label_4_4.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_0_3.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_2_4.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_4_6.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_0_1.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_1_0.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_5_0.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_2_6.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_5_6.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_2_1.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_4_5.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_0_5.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_5_3.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_3_4.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_3_0.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_2_5.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_3_1.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_4_0.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_2_2.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.week_6.setText(QCoreApplication.translate("MainWindow", u"\u661f\u671f\u5929", None))
        self.label_1_5.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_0_6.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_5_4.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_1_1.setText(QCoreApplication.translate("MainWindow", u"0", None))
    # retranslateUi

